### ISSUE TITLE
Tags view loads/lists all global tags

### ISSUE THREAD

**Issue by mejo-** [nextcloud/photos#1213]
**Describe the bug**
When opening the tag view in Nextcloud Photos, a list of all global tags is loaded first. Only afterwards, the view changes to display only tags the match your photos.

**To Reproduce**
1. Have many global tags
2. Tag a few of your photos
3. Open the tag view in photos app
4. See the list of tags being loaded first

**Screenshots**

**Comment by mejo-** [comment]
@marcelklehr

**Comment by ZID-TU-Graz** [comment]
We got a error message ("An error has occurred" / "Es ist ein Fehler aufgetreten ") when a tag URL (e.g. https://cloud.example.org/index.php/apps/photos/tags/TAGNAME)  is called. It seems that the problem only occurs, when the user does not have a photo with this tag.
So we guess, that our problem could also be solved, when this issue is solved.

**Comment by marcelklehr** [comment]
This is fixed in NC 25
