### ISSUE TITLE
Exceptions to folders, a whitelist blacklist system

### ISSUE THREAD

**Issue by Rmdhn1** [nextcloud/photos#1237]
**Is your feature request related to a problem? Please describe.**
Why should images i've backed up to nextcloud that's just schematics, designs, or even some screenshots SHOW UP in the photos app??

**Describe the solution you'd like**
make a blacklist whitelist system.

**Describe alternatives you've considered**
ditching nextcloud

**Additional context**

**Comment by skjnldsv** [comment]
Hey!
Sorry, but the tone of your issue is not how we contribute here.
If you wish to get some discussion or assitance going, please be neutral and offer some elaborate potential solution on how you think this issue could be resolved.

> make a blacklist whitelist system.

Some search could have lead you to this ticket for example #141 
If you wish to rephrase and/or adjust your issue, please consider opening a new one

https://nextcloud.com/contribute/code-of-conduct/
