### ISSUE TITLE
Support Groupfolders

### ISSUE THREAD

**Issue by xf-** [nextcloud/photos#129]
We use group folders app for shared space and most apps support them without any issue, but new photo app won't show any folders/images.

**Comment by skjnldsv** [comment]
cc @rullzer @icewind1991

**Comment by gabrielklein** [comment]
Same problem. I have a "group folder" with all my pictures. I share it with my wife.

When I do a
php -f occ maps:scan-photos 

Only my "personal folder" is scanned.

The "group folder" is in my case
/data/__groupfolders/1

It is not scanned and not displayed (on the map).

**Comment by gabrielklein** [comment]
Probably related to https://github.com/nextcloud/maps/issues/123

**Comment by jakobroehrl** [comment]
Unfortunately not possible to implement due to performance issues :(

**Comment by svenb1234** [comment]
What difference does it make whether a user's photo folder has 30.000 photos or a shared folder has 30.000 photos? Either the performance is up to job of handling large collections or not. Due to Smartphones and the ease of taking pictures these numbers are normal and Synology as well as Qnap have no issue in handling them. Neither in the web client nor the Android app. Yet both do not work well for Nextcloud.

**Comment by skjnldsv** [comment]
@svenb1234 depends on the technical implementation of the backend.

**Comment by rullzer** [comment]
Let me take a step back. What part are you looking to get groupfolders? Getting everything in your normal blogroll is hard. Having it in the shared part might be possible indeed.

**Comment by xf-** [comment]
@rullzer instead of sharing every photofolder form an event (and multiple people took photos), we use a shared folder to share them. Advantage to decrease the personal storage and increase the public/internal storage for shared stuff. Even a extra section with group folders would be fine, but since replacing the gallery, you need to go trough all the folders instead of using the image browser (now photos).

**Comment by darmbrust** [comment]
I'm not sure if they way I use nextcloud is the same as "group folders" - but without the ability for photos to show photos from shared folders, its useless to me.

I have an account that is only used by my phone to upload photos.

The folders that the phone uploads to are shared with my main account.

Photos ignores that those folders even exist, making it useless.

I also can't understand the logic that this can't be done due to "performance" issues.  Its another folder on the local server I have permissions to.  Sounds more like a design problem....
