### ISSUE TITLE
Correlation between GitHub version and displayed version in Nextcloud

### ISSUE THREAD

**Issue by phirestalker** [nextcloud/photos#1339]
I tried to search and did not find anyone else asking, and since there is no discussion section I am posting an issue.

I see here on GitHub versions such as 24.0.0.2 and 25.0.0.1, which I assume match the Nextcloud version. However, in the apps section on Nextcloud it shows I have version 1.6.0 and I hear about version 2.0 coming with object detection and facial recognition.

I came here looking to see how far away 2.0 might be and don't know how to link the versions. What is 1.6.0 here and what will 2.0 be?

Thanks.

**Comment by skjnldsv** [comment]
Hi,

We do not advertise changes in a simplified manner during the development phase.
You will find all the changes when the 25 final announcement is out

Regarding the versions, https://github.com/nextcloud/photos/tree/master is 26 now (since we're in RC), the https://github.com/nextcloud/photos/tree/stable25 branch is for 25, https://github.com/nextcloud/photos/tree/stable24 is for 24... etc

Photos is shipped with nextcloud releases. If you want to try 2.0, you can try the beta/rc releases https://download.nextcloud.com/server/prereleases/
