### ISSUE TITLE
No cropping photo design

### ISSUE THREAD

**Issue by grenzverkehr** [nextcloud/photos#143]
In "Photos" all photos are cropped square. This representation already exists in the grid view. But in "Photos" the photos (and videos) should be in the foreground. They should therefore be presented uncut. At least there should be an option in "Photos" to present photos and videos uncropped and to share this view via public link.

Here are a few nice examples:
https://www.flickr.com/photos/dmtoh/
https://www.photocase.de/p/491889
https://stock.adobe.com/contributor/204990950/weerasak

Photos and videos are also presented uncut in Google Photos.

**Comment by skjnldsv** [comment]
Reference from https://github.com/nextcloud/gallery/issues/550

![](https://user-images.githubusercontent.com/3404133/66809684-203e5200-ef2e-11e9-9e9c-fd11845e7020.png)

**Comment by linuxrrze** [comment]
The "old" "gallery" app also had a nice (over)view for images, even handling wide panorama pictures, while efficiently using the available space.
This allowed a really nice view for pictures of different formats.

The plain square image display of "photos" looks much less attractive (and is cutting of lots of information by cropping the images). 

I'd like to see a view mode like the one of the "gallery" app in the future.

**Comment by skjnldsv** [comment]
> I'd like to see a view mode like the one of the "gallery" app in the future.

I can already tell you this will not happens.
The layout was not satisfying us :)
Especially the panorama part, it was super hard to find te image you were looking for if you had tons of different sizes :confounded:

**Comment by linuxrrze** [comment]
Sorry to hear that - from my personal point of view it'll be much harder to find a panorama picture with the cropped view that's implemented now.

I've been using nextcloud/gallery extensively for my photos and I do have different sizes: I never had trouble with the "gallery" kind of view (I really like it) - so I'd disagree on that one.

I can however understand from a developer's perspective, that it's easier to do the square/crop thing (and it may even be required to make integration into nextcloud possible).

I'm just giving my point of view as a user - no offence meant ;-)

For now:
Will it be possible to use "gallery" instead of the "photo" app?

**Comment by skjnldsv** [comment]
> I'm just giving my point of view as a user - no offence meant ;-)

Of course! :)
None taken :hugs: 

> Will it be possible to use "gallery" instead of the "photo" app?

No, the gallery is now deprecated, it was causing more issues than any good stuff.


> I can however understand from a developer's perspective, that it's easier to do the square/crop thing (and it may even be required to make integration into nextcloud possible).

It's not about easiness, it's about what others do and what the user expect nowadays. Please see #145 for extensive discussion about this.

**Comment by linuxrrze** [comment]
Thanks for the hint to the other discussion.

If I got it right, there are plans to improve the view further in coming releases, and the current state is limited because version 18 needed to be released on time.
And as the screenshots posted as reference in thread #145 look quite nice, I'm hopeful that the photos app will get there somewhen soon ;-)

**Comment by nemihome** [comment]
I would also prefer a non cropping option but I'm ok with square which meens there is some space whasted but you see the full pic. That the same like the people which streched the 4:3 pictures in tv to 16:9 because the tv has this size. Some like that some don't.

**Comment by grenzverkehr** [comment]
**Tiled View (row)**
- Wikipedia: https://en.wikipedia.org/wiki/Help:Gallery_tag (packed)
- Google Image: https://www.google.com/search?q=forest&tbm=isch
- Getty Images: https://www.gettyimages.com/fotos/forest
- Photocase: https://www.photocase.com/photos/editors-picks (Editor's Picks)
- Flickr, Google Photos, Amazon Photos, Microsoft Photos, Adobe Stock, 123RF, Shutterstock, pixabay

**Tiled View (column)**
- CC Search: https://ccsearch.creativecommons.org/search?q=forest
- Unsplash: https://unsplash.com/
- Photocase: https://www.photocase.com/photos/trends (Trends)

**Square View (uncroped)**
- Wikipedia: https://en.wikipedia.org/wiki/Help:Gallery_tag (traditional)
- Photocase: https://www.photocase.com/fotos (New Photos)
- iPhoto (Search)

**Square View (croped)**
- Android Gallery, iPhoto

Almost all applications that are designed to present photos do without cropping and show the photos tiled view.

**Comment by nemihome** [comment]
But what does this mean? Is it good because nearly everyone does it? :)

In Jalbum it is possible to set an option what you like depending on skin.

Looks like this (Tiles view):
![image](https://user-images.githubusercontent.com/60146462/72934940-c89d5700-3d64-11ea-8c4d-1d3f83f06092.png)

**Comment by jancborchardt** [comment]
It’s not about the mass of apps, but who has most users – and by extension what people are most used to. @grenzverkehr That is, Android Gallery and iPhoto use cropped design, so this is a big reason why we went for it as the default and first implementation. :)

Yes, going forward there will likely be an option for this in the future as specified in https://github.com/nextcloud/photos/issues/145#issuecomment-542080887 – this was already referenced by @skjnldsv above so not sure what else needs to be discussed? :)

**Comment by grenzverkehr** [comment]
Just one more thought: for the smartphone you may be right about the distribution but certainly not about laptops / desktops.

**Comment by FanchTheSystem** [comment]
+1 I would like my photo to not be cropped too ! It some kind of breaking my own work as a phographer...

File app already show cropped photo, and allow search and management of this kind of file.
Maybe you should think about : 
- Why people will use photo app instead of file app ? 
- What are the use case you want to answer in a so called "photo app" ? 

For example my personal workflow is : I use nextcloud to send shared link to people who are concerned by photo I take, I want them to see all the photo as they are, so they can choose which one they want to download.

**Comment by skjnldsv** [comment]
I would like to thanks everyone for their feedback! It really helps! 🤗

**Comment by civita** [comment]
I also want justified layout as the [Gallery App](https://github.com/nextcloud/gallery) has. It looks better and saves some spaces. For me, I have both portrait and landscape photos. With the justified layout, I can tell the aspect ratio efficiently without click on each photo. Please add such an option for users to choose with layout shown in the Photo app.

**Comment by dennorske** [comment]
https://fox.cla.ws/ uses a nice concept of tiling, using all the available space. Of course, some pictures appear to be a bit cropped and it can be weird for very wide pictures.
Otherwise is can remind a bit about Google photos when you zoom in on your list view

**Comment by jancborchardt** [comment]
@skjnldsv let’s have a settings switch to change the view: "Don’t crop previews", unchecked by default. It will then use the view macOS photos has.

**Comment by Georg-Git** [comment]
@jancborchardt at least for sharing pictures I prefer the nicer view of a non cropped preview. 

When You will stay with cropped previews as default I would request a parameter to be accepted in shared links e.g.: ?preview=noncropped

**Comment by Georg-Git** [comment]
@jancborchardt "not sure what else needs to be discussed?"

Because You still do not have accepted our use cases and users demands:

@grenzverkehr:
"to present photos and videos uncropped and to share this view via public link"
5 Likes!

@linuxrrze: "I never had trouble with the "gallery" kind of view (I really like it)"
2 Likes!

@FanchTheSystem: "I would like my photo to not be cropped too ! It some kind of breaking my own work as a photographer..."
5 Likes!

@civita: "I also want justified layout as the Gallery App has."
1 Like!

I found only one user comment in favour of squared grid view - without any likes.
All the other users preferred a non cropped view - obviously as default view.

But what is Your last answer under all these user remarks:
Photo App will stay with cropped view as default.
After all You still thinking at least about a cropped view, but not as default.

So sending a public link to my photo album to new users will start now in the fileview as default - and when the new user will find the icon, he is perhaps able to switch to the squared view nobody wants.

But as far as I understood the comments of the users in this and also in other threads: we want to send a public link to a photo album and this should be presented with non cropped previews icons - as default - not as fileview as default and not as squared view as default.

**Comment by jancborchardt** [comment]
@Georg-Git don't worry, we will look into it.

Regarding the collected statistics on the likes: Remember that people who are absolutely fine with the cropped view will not show up here since they have no issue with it. It's an _issue_ tracker, so it's not a proper tool to take a vote.

**Comment by Georg-Git** [comment]
And again a hit in the face of every user taking time to file a issue and give You hints for optimization. Git issues does not really matter to @jancborchardt - Git users are only a annoying minority....

Frank @karlitschek in a interview about owncloud:
"Auch die Entwicklercommunity ist geschrumpft, da das Unternehmen damals schlechte Entscheidungen getroffen hat. Ich habe damals versucht, das zu korrigieren, was mir leider nicht gelungen ist."

Now Frank is not using the photo app of nextcloud - perhaps because he is preferring a noncropped view as default:

https://karlitschek.de/photos/#

**Comment by jancborchardt** [comment]
Hi @Georg-Git :) As said, the main issue here is that we have to find the time to implement this. Whenever we get to it, whatever people choose will be remembered, and also shown for people you share with via link.

Thanks for your patience and feedback. :heart:

**Comment by Mikescops** [comment]
FYI

![image](https://user-images.githubusercontent.com/4266283/96224363-c254a800-0f8f-11eb-9769-f8d6da61f651.png)

**Comment by grenzverkehr** [comment]
Thank you very much for the implementation of the new photo view. But unfortunately it does not yet meet my requirements as a photographer. [See this new issue](https://github.com/nextcloud/photos/issues/496)
