### ISSUE TITLE
Ability to change main photo on album 

### ISSUE THREAD

**Issue by AndyXheli** [nextcloud/photos#1593]
Currently  the main photos on the album is automatically select, it would be nice to have an option to change the main photo from the phots that are in the album

**Comment by simonspa** [comment]
This would mainly require front-end work to add a button. In the backend, the album cover is stored as `last_added_photo`. Changing this should be straight forward.

Anyone up for helping me adding a possibility for this in the front-end?

**Comment by shalak** [comment]
Would be nice to have several options:
- always show last added photo (I understand that this is the current behavior)
- show chosen photo
- show the most recent photo by file creation date
- show the most recent photo by EXIF

**Comment by MAF2510** [comment]
I would also like to have this function and don't understand why it doesn't already exist.
It is important to personalize the view of the albums. 👍

**Comment by Oleg78** [comment]
There is a workaround. Just remove desired photo from the album and add it again. Now this is the main photo, the last one added.

**Comment by spanezz** [comment]
Sometimes the last photo uploaded might be a very inappropriate representative for an album. Think of a culture holiday trip with lots of beautiful architectural photos where the last photo uploaded is the embarassing picture of a friend who accidentally got drunk on the last night. This might be especially inappropriate if the album gets shared.

Fair enough, one finds this issue and learns it's the last photo uploaded rather than the last by EXIF time or modification time, and one can awkwardly go and fix it by removing/adding a more appropriate photo. Album is usable again.

Still, this is the kind of feature one may find oneself in a situation where one really wants it as an easily reachable main feature, rather than a tricky to find workaround

**Comment by spanezz** [comment]
I just found out this [can be done in Memories](https://www.reddit.com/r/NextCloud/comments/1bjwgqo/memories_v7_changelog_and_upgrade_notes/) by selecting the photo in the album with the tick mark: the menu will then have "Set as cover image".

The option is not available, however, if one clicks on the image to open it.

**Comment by justresisting** [comment]
> I just found out this [can be done in Memories](https://www.reddit.com/r/NextCloud/comments/1bjwgqo/memories_v7_changelog_and_upgrade_notes/) by selecting the photo in the album with the tick mark: the menu will then have "Set as cover image".
> 
> The option is not available, however, if one clicks on the image to open it.

This is exactly what I was looking for and almost missed it because it was buried in this thread. 

FYI, as a user, I don't need any options for how this is applied, like EXIF or by date created/modified, etc. Giving me the ability to pick whatever image I want as the album cover is all I need. 

The `add as cover image` option should really be included when you open the picture up and not just when you click on the picture itself, prior to opening it up. Should I make an issue for that?
