### ISSUE TITLE
Album sharing broken

### ISSUE THREAD

**Issue by tatrapikao** [nextcloud/photos#1694]
**Describe the bug**
Can't access shared album. Album shows in the list "shared albums" but if i try to access it i get "an error occured" on an empty Page.
![error](https://user-images.githubusercontent.com/77448960/224078712-1bc562b4-0905-47ee-b9d6-776aad7791b0.png)
![error1](https://user-images.githubusercontent.com/77448960/224078384-bfff6c22-b1fd-4943-8d02-aafb5dd5284f.png)
 On The second Album shared by another person i can infact open the album and see the previews, but enlarging the image brings up the following error:
![error3](https://user-images.githubusercontent.com/77448960/224079096-9efd14cc-81f2-495a-8d3a-aaa52aec0c30.png)

**To Reproduce**

see above - tried to reproduce instead got a different error...

**Expected behavior**
Access the  albums another person shared with me.

**Desktop (please complete the following information):**
tested on Firefox110 and Chromium110 on Ubuntu 22.04 and on OSX
-> the second error seems to appear only with firefox.

**Comment by umgfoin** [comment]
Confirmed for _NC 26.0.1, [photos 2.3.0 git/[master]](https://github.com/nextcloud/photos/commit/253176ffe651868b1554c3dcf7cd2e6ed36d122a), PHP 8.2_

@artonge
PHP-log:
`Could not check compatibility between OCA\Photos\Sabre\Album\PublicAlbumRoot::getChild($name): OCA\Photos\Sabre\Album\PublicAlbumPhoto and OCA\Photos\Sabre\Album\AlbumRoot::getChild($name): OCA\Photos\Sabre\Album\AlbumPhoto, because class OCA\Photos\Sabre\Album\PublicAlbumPhoto is not available at /[NEXTCLOUD_ROOT]/apps/photos/lib/Sabre/Album/PublicAlbumRoot.php#82`

**Comment by artonge** [comment]
I was not able to reproduce.
Which version are you using, v26.0.1?
Can you check that `lib/Sabre/Album/PublicAlbumPhoto.php` exist?

**Comment by joshtrichards** [comment]
@tatrapikao What appears in your Nextcloud log when you reproduce this behavior? What appears in your browser inspector, under both *Console* and the *Network* tab when doing so?

**Comment by tatrapikao** [comment]
I am happy to announce that album sharing at the moment works for me at one would expect.
