### ISSUE TITLE
Photos app ServiceWorker issue in NextcloudPI no SSL

### ISSUE THREAD

**Issue by kozfelipe** [nextcloud/photos#1732]
hello
I am running latest NextcloudPi v1.51.0 docker container (01-22-23)
NextCloud 25.0.3.2
my raspberry is under a residential ISP that blocks standard web ports hence I cannot issue letsencrypt ssl certificate.
when I try to upload files using Photos app I get this error that prevents HTTP/PUT

![image](https://user-images.githubusercontent.com/25208457/230960078-d982a2b7-b3f9-45a1-aee7-3aa3b27b38f9.png)
`Failed to register a ServiceWorker` `An SSL certificate error occurred when fetching the script`

![image](https://user-images.githubusercontent.com/25208457/230960619-82be0db6-1ff8-49b7-be20-5bae22e84f7f.png)

**Comment by joshtrichards** [comment]
So are you using a self-signed certificate or none at all?

You can still setup Lets Encrypt using an alternative verification mode like DNS:

https://letsencrypt.org/docs/challenge-types/

e.g.

https://help.nextcloud.com/t/how-to-get-certificate-with-letsencrypt-using-dns-to-verify-domain/126329

**Comment by kozfelipe** [comment]
hi @joshtrichards thanks for the tip
although I could'nt make it work through the guide as I am using no-ip DDNS

**Comment by joshtrichards** [comment]
Gotcha. DDNS itself doesn't prevent adding TXT records, but that looks like maybe a service level (?) restriction by No-IP.  Bummer.

There are some potential workarounds, but they're hacks - e.g.

https://stackoverflow.com/questions/38728176/can-you-use-a-service-worker-with-a-self-signed-certificate

(I've used them for testing).

I'd still recommend a real cert. :-)

Unfortunately, the issue you're facing isn't a bug or restriction in Photos (or NC). It's a browser / general web security measure so... I suggest closing this Issue here since it's outside this repository's scope. 

Feel free to follow-up at the [Nextcloud Help Forum](https://help.nextcloud.com/) though if you continue to get stuck or look for workarounds!

**Comment by kozfelipe** [comment]
Thanks for the feedback
I will replace NextcloudPi for the standard Nextcloud setup in order to workaround the cert.
this docker version is too advanced for my scenario
