### ISSUE TITLE
PHP Fatal error:  Allowed memory size exhausted on cron job

### ISSUE THREAD

**Issue by wwwdesign** [nextcloud/photos#1735]
**Describe the bug**
I'm getting repeatedly error warnings from the Cron Daemon:

```
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 528384 bytes) in /var/www/vhosts/mysite.net/cloudy/apps/photos/vendor/hexogen/kdtree/src/ItemList.php on line 49
```

**To Reproduce**
1. Wait for cron to run

**Expected behavior**
Cron daemon running without error

**Server (please complete the following information):**
 - Version 26
 - PHP 8.1.17
 - memory_limit 512M

**Additional context**
Error appeared last friday for the first time

**Comment by nicrame** [comment]
What is Your PHP memory limit (memory_limit in php.ini)? If it's low try to make it higher like 512MB.

**Comment by tegger2000** [comment]
hi, i had the same problem. add "-dmemory_limit=-1" to your cron job, i.e. "/usr/local/php81/bin/php -dmemory_limit=-1 occ photos:update-1000-cities"

**Comment by Sedeniono** [comment]
I am running a small private nextcloud instance in a shared hosting environment. I also saw the following lines when background jobs were run:
```
"Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) at <nc path>/apps/photos/lib/Service/ReverseGeoCoderService.php#151"
"Allowed memory size of 134217728 bytes exhausted (tried to allocate 4096 bytes) at <nc path>/apps/photos/vendor/hexogen/kdtree/src/Point.php#20"
```
They appeared after I uploaded some geotagged photos. Deleting the photos fixed the problem. Alternatively, disabling the photo app also "fixed" the issue (but, of course, then the app is no longer available).

As explained in the posts above, the issue is, of course, insufficient memory. The thing is: Without upgrading to a more expensive shared hosting plan, I am stuck with 128MB of memory. So I cannot increase it by simply editing some php configuration or cron job. And for my single-user use case it was sufficient till now. Is there maybe some way to disable the geotagging feature of the photos app?

Also note: The minimum memory according to the [nextcloud manual](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html) is 128MB, so I would expect the photos app to work with that. So one might actually argue it is a photos app bug (or, alternatively, the manual needs to be updated).

**Comment by joshtrichards** [comment]
>  Is there maybe some way to disable the geotagging feature of the photos app?

`occ config:app:set --value='1' photos disable_places` should work in the latest Photos within v29.

> Also note: The minimum memory according to the [nextcloud manual](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html) is 128MB, so I would expect the photos app to work with that. So one might actually argue it is a photos app bug (or, alternatively, the manual needs to be updated).

That's the minimum that is even viable, but >=512 is recommended. It also says memory needs vary greatly depending on apps/etc. :-)

**Comment by joshtrichards** [comment]
@Sedeniono Doc clarification pending for memory constrained environments. Thanks for pointing that out: nextcloud/documentation#11775
