### ISSUE TITLE
Photo App on Website breaks webdav access / nextcloud freezes / high cpu

### ISSUE THREAD

**Issue by Nazgile94** [nextcloud/photos#1920]
**Describe the bug**

**To Reproduce**

connect nextcloud as webdav storage on windows

**Expected behavior**
after i have connected nextcloud over webdav with my windows 11 machine and open the photo app, no pictures are loading and nextcloud freezes , need to manually restart - using nc 27 - AIO

**Screenshots**

**Desktop (please complete the following information):**
Windows 11
latest chrome

**Browser log**
```
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

just lot of jquery errors, no critical
```

**Additional context**

using nextcloud AIO with NC 27 on unraid (docker) -- all working so far.
but as soon i use webdav and browsing pictures on web via photos app, photos preview doesnt load, nextcloud frezzes and need to manually restart the containers
using npm as proxy, ip is setted under trusted proxies.
access works fine over domain etc etc. just webdav problem as soon i open photop app 

if i remove the webdav connection, all works fine.

Containers
 Apache 
 Database 
 Nextcloud
 Notify Push 
 Redis
 Collabora
 ClamAV
 Imaginary
 Fulltextsearch

**Comment by joshtrichards** [comment]
Can you clarify something: are you saying that using the Photos app causes the Nextcloud web interface + WebDAV connections to freeze? Or are you saying that using the WebDAV connection causes the Photos app and Nextcloud web interface to freeze?

This sounds like a resource issue. Loading Photos is going to generate preview images on-demand and spike the CPU. On a lower end CPU this can overload it sometimes. You can modify the parameters used for generating previews in Nextcloud using methods described in the Admin Manual (cpu concurrency), but that's outside the scope of the Photos app.

What are the CPU and memory specs of your host?

The output of your Nextcloud logs may also provide some clues.

You may also want to open a Discussion or Issue over at https://github.com/nextcloud/all-in-one since the AIO environment is fairly self-contained.

**Comment by Nazgile94** [comment]
Webdav caused Photo App and nextcloud to freeze

But it seems to be fixed

Created an apppassword for webdav (without 2fa)

Used this for webdav Connection

Annnnd pointed my nextcloud Domain on my adguard to The local IP of my npm Container, now it Connects locally instead over wan Back to me.
