### ISSUE TITLE
No folder hierarchy in the "Your albums" tab is confusing

### ISSUE THREAD

**Issue by nimarb** [nextcloud/photos#197]
Hello,

Version used: NC 18.0.1 upgraded from NC17; Using LDAP backend.

Within our org, we have a shared media folder. The folder is divided into subfolders by date like this:

```
|-- 2018
|   |-- event1
|   |-- event2
|   `-- event3
|-- 2019
|   |-- event1
|   |-- event2
|   `-- event3
`-- 2020
    |-- event1
    |-- event2
    `-- event3
```

This goes back years and contains hundreds of event folders.

The problem is, that when clicking on "Your albums" in the new photos app, all folders and subfolders show up at the same time in a completely flat hierarchy, so we see hundreds of "event1, event1" etc. folders without any context. Sorting by folder name is also not possible.

I expect there to be a hierarchy, similar to the previous gallery app, which goes by the folder hierarchy. Or perhaps an additional tab "Your Folders" and "Shared Folders" where the folder hierarchy is preserved.

Thanks a ton & happy to provide more debug details.

Related issue: #120

**Comment by BloodyIron** [comment]
Yeah I just upgraded to NC 18.0.1 too, and I was previously using the hierarchy to organise my photos/images for events and many other things, and now that's just out the window. I can't even "search" for what I want to find.

I like how much faster it is, in parts, but this really blows away a good chunk of my organisation. I for one would like to find a balance between the flat structure and folder structure.

**Comment by skjnldsv** [comment]
@jancborchardt

**Comment by Kourai** [comment]
Same here, I have about 20 000 pictures, maybe more.
Everything is organized in folders (Mainly Year folders, then Month folder), and I can't find anything within the new photo app... So I really this enhancement come soon cause the photo app is quite good and beautiful, but there is no way on earth for me to re-organized those pictures....

(Also flat structure is evil! How can you have stuff in the right place that way....)

**Comment by jancborchardt** [comment]
Good points, just some clarification on the intention:
- The idea is that people shouldn’t need to do additional work to organize their photos, it should happen automatically (compare to e.g. macOS / iOS Photos)
- The folder structure is already available exactly like this in the Files grid view
- The issue with year folders (and month folders as well) is what happens when a vacation or event is during new years (like skiing for example) – putting it into either or is just confusing.

That’s not to say we won’t do folders, but just to keep this in mind. :) It’s still very early days in development and some things are not realized as per our vision yet, which maybe makes it difficult to see where we want to go with this.

cc @karlitschek as well, especially on if we should have the normal folder structure in the albums view or a separate "Folders" view (which could also switch to the Files app grid view?), or keep it like it is.

**Comment by BloodyIron** [comment]
> Good points, just some clarification on the intention:
> 
> * The idea is that people shouldn’t need to do additional work to organize their photos, it should happen automatically (compare to e.g. macOS / iOS Photos)
> * The folder structure is already available exactly like this in the Files grid view
> * The issue with year folders (and month folders as well) is what happens when a vacation or event is during new years (like skiing for example) – putting it into either or is just confusing.
> 
> That’s not to say we won’t do folders, but just to keep this in mind. :) It’s still very early days in development and some things are not realized as per our vision yet, which maybe makes it difficult to see where we want to go with this.
> 
> cc @karlitschek as well, especially on if we should have the normal folder structure in the albums view or a separate "Folders" view (which could also switch to the Files app grid view?), or keep it like it is.


First, if this was "early days in development" then why did you guys just "forcefully" (so to say) roll out such a drastic UX change? That's akin to rolling out Alpha/Beta code out to Prod. Bad form!

Second, with the previous gallery functionality, the folders had previews of pictures inside it, and that really helped me traverse them. I don't want to just look at the file names like in the files app, I want to LOOK at the pictures. And having this as a forced-flat structure really destroys that organisation.

I'm not saying this isn't a step forward, but it most certainly is a step backwards in some UX regards too. I use the Gallery (Photos) to help me rapidly seek pictures that I'm looking for (I run events, so these pictures can be used for promotions, etc). And as the UX stands today, my job is drastically harder now.

Hell, I can't even tell how it's sorted at all in the flat style! Doesn't seem to be alphabetical, or otherwise (also, really need sorting here).

Another thing I'd like to add (which is off-topic), is that Photos seems in some regards slower to load, and in other regards faster. Takes a bit of explaining, but it sounds like there's improvements under the hood that aren't quite complete, from a performance perspective.

I do appreciate this work, but I for one really would like a mode where it worked similarly to how the folder structure worked previously in Gallery. I'd be fine toggling between each (and if I could set a default mode that'd be stellar too).

**Comment by palto42** [comment]
I wonder how many users have tested the new Photos app in alpha/beta.
Just upgraded from 17 and very disappointed with this new app.
The vision might be good, but this doesn't look ready for production and it would have been much better to support both old Gallery app and new Photos app in parallel for at least one major release to get sufficient feedback from a wider community.

My main concern is as well the top level view in "Your Albums" which has no useful order for me so that I can't easily browse to photos at specific year/month. The timeline view is only useful for the most recent photos.

**Comment by skjnldsv** [comment]
> I can't easily browse to photos at specific year/month.

Planned :)
https://github.com/nextcloud/photos/pull/125
#45

**Comment by palto42** [comment]
> > I can't easily browse to photos at specific year/month.
> 
> Planned :)
> #125
> #45

Thanks for pointing me to this feature development, but not sure if it will provide what I'm missing. It just seems to add date separators into the timeline, but can't see anything to jump to a specific date, e.g. "June 2013"

**Comment by skjnldsv** [comment]
I guess this is a multi step process :)
We're not reinventing the wheel, we're taking inspirations on what is already widely done out there (macos iPhotos, Google Photos, Android gallery...)

I guess having a slider to go to date would be a second very important step? What do you think? Do you see other good ideas? :)

**Comment by palto42** [comment]
I think that a single slider is not very practical if you want to browse multiple years time span. 
Maybe a date picker similar to this one be used to jump in the timeline (just as a clickable icon, no need to show the date)? https://jqueryui.com/datepicker/

**Comment by skjnldsv** [comment]
Why not both? :D
I was thinking about a slider like the forum :)
