### ISSUE TITLE
Fotos

### ISSUE THREAD

**Issue by htttito** [nextcloud/photos#201]
Sorry Entwickler...die alte App war viel besser. Nur meine Meinung...

- Deine Alben: Die Alben werden erst nach Minutenlangen warten angezeigt...wenn überhaupt
- Deine Alben: Ein Klick darauf und es bringt das ganze System fast zum Einbruch (Browser, apache,....)
- Deine Fotos: Keine Möglichkeit Fotos zu sortieren oder sonst was...

Ist die App ist noch nicht fertig?
Dann bitte nicht auf "Offiziell" und online stellen...

Danke!

**Comment by RobertZenz** [comment]
[You can reenable the old gallery](https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949/18).

The worst part for me is that the share-links of the old Gallery are being silently dropped. That means all shares that I've publicized are dead with the update (without reenabling Gallery).

**Comment by skjnldsv** [comment]
> The worst part for me is that the share-links of the old Gallery are being silently dropped. That means all shares that I've publicized are dead with the update (without reenabling Gallery).

The shares still exists as a file share, right?
So make sure to redirect the old gallery links would be a nice thing to have for #128 :)

**Comment by skjnldsv** [comment]
@htttito Sorry, but we use English here to manage issues and communication :)
I'm sad to hear the new app doesn't fit your needs. But I don't see a really incentive to help us improve with your issue, but rather just a complaint. WHich is relly not what this trcker is here for ;)

Please open a new issue with proper template to help us improve your performances issues

**Comment by RobertZenz** [comment]
> So make sure to redirect the old gallery links would be a nice thing to have for #128 :)

How was it released without that anyway? I mean, it seems like Photos is still lacking in quite some areas, how was the decision made to drop Gallery completely without having a valid replacement?

**Comment by htttito** [comment]
@skjnldsv
Sorry John...Nextcloud and many Apps are very great :-)!
But we are not alone with that opinion for the Photo App, look here:
[(https://help.nextcloud.com/t/new-photo-app-in-nextcloud-18/69949)]

**Comment by skjnldsv** [comment]
@htttito I don't argue with that :)
It seems to have quite a few people being unsatisfied with the current state.
Though I also heard a lot of people being happy, but you usually get more complains than congratulations online ;)

Nonetheless, this is not an issue, we aim to improve, this app was migrated and rewritten because the old state was impossible for us to add any new features. Now this is easier to maintain and we finally can work on this awesome app again! To improve it! So feel free to help us specify where you would like the app to improve by up-voting existing issues/feature requests or by creating missing ones on this repository :rocket: 

That is the power of a community-driven open source project! :tada:

**Comment by RobertZenz** [comment]
> Though I also heard a lot of people being happy, but you usually get more complains than congratulations on the web ;)

That's certainly true, but using it as an excuse is really just hiding behind it. And I'm quite tired of hearing "people will always complain" used as an excuse to *not* listen to complains.

 > Nonetheless, this is not an issue...

Well, everybody complaining sees this slightly different.

 > ...this app was migrated and rewritten because the old state was impossible for us to add any new features.

As somebody who has seen and worked on 20+ year old codebases, I can say that your use of "impossible" is not correct here. Of course, projects tend to accumulate a lot of cruft over time, but dropping it every few years and starting anew, with less features, with the next big shiny thing, is not going to solve *anything*. Not for the developers, because they will constantly do the same work over and over again (just differently), not for the users, as they will never see a "feature complete" version.

 > That is the power of a community-driven open source project!

So, where did the public discussion take place to drop Gallery and replace it with Photos?

---

Of course, I should not complain because I'm getting it for free yada yada. But you know, if NextCloud would offer a private tier, I'd *happily* pay for it to get my issues fixed or at least looked at *once*. Because my time is not free either, and spending several hours after each update to try to fix things that broke tends to get annoying.

**Comment by skjnldsv** [comment]
> That's certainly true, but using it as an excuse is really just hiding behind it. And I'm quite tired of hearing "people will always complain" used as an excuse to _not_ listen to complains.

Have you been to the impression I am not listening to people issues and trying to fullfill people's need here?

> So, where did the public discussion take place to drop Gallery and replace it with Photos?

I'll strongly suggest you get involve in Nextcloud's project and come to our next contributor week. Maybe you'll be able to discuss and see how we work.

**Comment by jospoortvliet** [comment]
> So, where did the public discussion take place to drop Gallery and replace it with Photos?
I think that that was at this contributor week:
https://nextcloud.com/blog/time-for-the-next-contributor-week-in-berlin/

You can join the next one, we'll announce it this week and it will be in about a month I believe. There you can help and join the conversation about new features and improvements. Alternatively, join the Nextcloud Conference...

We don't discuss these things on forums and such, in no small part because online discussions often become unpleasant and nonconstructive. People feel strongly about issues that affect them, even if they are a tiny minority, for example. That is understandable, of course (I also care more about issues that hit me) but disrupts the decision making process which has to focus on the bigger picture. In person, this is easier to handle.

If travel to contributor weeks or conferences is a problem - we are happy to sponsor contributors.

**Comment by nickvergessen** [comment]
Let's turn this issue into something productive instead.

To fix the "broken" and "missing" share links, add the follow redirect to your htaccess:

```htaccess
<IfModule mod_rewrite.c>
  RewriteEngine on

  RewriteCond %{REQUEST_URI} ^/index\.php/apps/gallery/s/(.+)/(.+)$
  RewriteRule .* /index.php/s/%1 [L,R=301,QSA]
  RewriteCond %{REQUEST_URI} ^/index\.php/apps/gallery/s/(.+)$
  RewriteRule .* /index.php/s/%1 [L,R=301,QSA]
</IfModule>
```
