### ISSUE TITLE
Upload the first image to an album doesn't work

### ISSUE THREAD

**Issue by ShGKme** [nextcloud/photos#2191]
When users open an album with photos, there is an "Add" button with two options:

![image](https://github.com/nextcloud/photos/assets/25978914/fb32862e-89e4-4f52-86b1-18b52409f3ff)

1. **Upload files** - allows selecting a local file, upload it **to the current album**
2. **Add photos to this album** - opens files picker
   ![image](https://github.com/nextcloud/photos/assets/25978914/6a7d3a21-1f4e-4cdb-902c-d092500af0a0)
   Then this **FilePicker** allows 2 actions:
   2.1. **Select** some existing files to add selected photos to the album
   2.2. **Add** to upload a new photo

---

On p.2.2. there are two issues:
1. Though this dialog was opened by **"Add photos to this album"** action, this button doesn't upload new file to **this album** but to the root photos folder for further selecting. 
2. Then the first photo is uploaded, this upload fails with 404 because it uploads a file via `dav/files` and does not create the photos directory managed by `dav/photos`.

---

Proposals:
1. "Add" button on the file picker should upload files to the album the same as the **"Add"** button
2. It should use `dav/photos`

**Comment by artonge** [comment]
That would not be aligned with what the user expect from this picker.
Again, this is two separated process, first upload a new file to your file, then pick it to add it to the album.

**Comment by jancborchardt** [comment]
cc @nimishavijay since she is the main designer on Photos. :)

**Comment by ShGKme** [comment]
> Another alternative would be to create the directory from the frontend if the PUT request fails.

This would require `@nextcloud/uploader` update. We can handle 404, but we cannot restart uploading.

**Comment by nimishavijay** [comment]
From a UX perspective, we should allow people a simple way to upload directly into the album. (In fact, I would argue it even makes sense to get rid of the "Upload files" button in the "Add" menu and directly show the file picker with the upload button there, but that's a follow up issue) 

Selecting the photos again is a cumbersome process indeed, especially if people are uploading, for eg. 100 photos at a time. Is there any way to upload the files and automatically have them be selected, so that the only action the user needs to do is click on "Add to album"? So the flow would be:

> Click `Add photos to this album`
photo picker opens 
Click `Add` button 
local file manager opens
select photos 
Click the open button in the local file manager
wait for your photos to be uploaded
see that your uploaded photos have been selected
additionally select any more photos if you want
Click on `Add to album_1`

Would that be possible technically? :)

**Comment by artonge** [comment]
> Would that be possible technically? :)

Yes :).

So, just to make sure, in the FilePicker, when the user uploads new files with the "+ Add" button, we should not directly add the files to the album, but only preselect them, and let the user confirm the action by clicking on the "Add to ..." button. Right?

**Comment by nimishavijay** [comment]
Yes, that sounds good to me :) Additionally, 2 points to make things clearer: 
- [ ] we should change the wording in the photo picker from "Add" to "Upload from device"
- [ ] would it also be possible to show a indication of the total number of photos selected? So a text that says "10 items selected" on the left of the "Add to album" button 

@ShGKme would this solve the issue? You are able to easily add photos to your album, but it wouldn't seem like a "2-step process" :)

**Comment by jancborchardt** [comment]
> I would argue it even makes sense to get rid of the "Upload files" button in the "Add" menu and directly show the file picker with the upload button there

@nimishavijay just for reference, I totally agree with this. I found the 2-step process with the same 2 options at both steps confusing as well.
