### ISSUE TITLE
[BITV]: Not possible to add already selected photos to the album via keyboard

### ISSUE THREAD

**Issue by JuliaKirschenheuter** [nextcloud/photos#2238]
1. Create an album
2. Try to select some photos and add them to the album via keyboard

![Peek 2024-01-08 18-05](https://github.com/nextcloud/photos/assets/6078378/e349391f-40c2-4e1c-9e75-2735872fdde7)

It is not possible to reach "Add to ..." and "Add" buttons via keyboard

**Comment by Pytal** [comment]
This issue seems to involve multiple dependencies including @nextcloud/files, @nextcloud/upload, and @nextcloud/vue with changed beta APIs making it slightly confusing

When I checkout the @nextcloud/upload package to v1.0.4 and link it locally + src changes the bug is resolved but updating to v1.0.4 from npm in package.json does not seem to work, any ideas why this might be @ShGKme?

**Comment by Pytal** [comment]
Draft https://github.com/nextcloud/photos/pull/2256 was closed due to scope creeping into Folder/Node API migration territory

Would you be able to tackle this migration @artonge?

**Comment by Pytal** [comment]
If the behaviour in the screencast is not seen, you can instead observe the following error in the console
![image](https://github.com/nextcloud/photos/assets/24800714/3e653e0e-40fb-43ae-9026-0786a4c3d143)

**Comment by JuliaKirschenheuter** [comment]
Thanks @Pytal!

**Comment by Pytal** [comment]
This is a tricky bug as we use focus trap + virtual scrolling here. Focus trap finds the initial tabbable nodes but as you scroll the elements are rerendered and seems to cause the glitch. `updateContainerElements` does not seem to work, still not sure why though.

According to the `focusin` event the next node is correctly focused but immediately afterwards the focus is moved to `body`

Draft semi-working patch to bring back focus to the correct next element in https://github.com/Pytal/focus-trap/pull/1

**Comment by Pytal** [comment]
Regarding the virtual scrolling part, there is a new related bug with the virtual-scrolled files list where if you have many files and tab past the last file to the start of the page and then back into the list it will focus not on the first file but on the first currently rendered file i.e. 90th file row instead of the first

I believe there was some exception made for infinite scrolling before so maybe not an issue

**Comment by ShGKme** [comment]
Can we disable `focus-trap` here and implement our own simple focus trap?

**Comment by Pytal** [comment]
> Can we disable `focus-trap` here and implement our own simple focus trap?

Just tried and seems to make it worse, tabbing at the glitch point jumps straight to the bottom instead of the next photo

**Comment by JuliaKirschenheuter** [comment]
close as done
