### ISSUE TITLE
Shared folders are not paginated

### ISSUE THREAD

**Issue by ValdasK** [nextcloud/photos#540]
**Describe the bug**
Trying to understand how things work (for other feature request) I'v noticed that when you open shared folder, its contents are not paginated (everything opens at once) like when you open non-shared one (thumbs are loaded in chunks), which leads to poor performance and occasionally stalls browser tab.

**To Reproduce**
1. Go to shared folder with plenty of photos (in my case, 4 000)
2. Click on folder containing those photos
3. Notice that thousands of requests for thumbnails are made to server, and browser freezes for a while

**Expected behavior**
First N photos should be loaded, all others should wait until scroll down like in other categories.

(using NC 19.0.4)

**Comment by skjnldsv** [comment]
This should be fixed with nc21 :)
It's mostly because the virtual grid (not rendering the full list and faking the scrollable page height) was only enabled on the timeline view.

We changed and improved a lot for 21. I'll let thi sone opened until you're able to try the release in a few months :wink:

**Comment by joshtrichards** [comment]
@ValdasK Okay to close this old issue out? :)
