### ISSUE TITLE
Preview Caching: When, Where?

### ISSUE THREAD

**Issue by hiranchaudhuri1** [nextcloud/photos#562]
I started using the Photos app recently, and so far my pictures are on external storage that I mounted readonly.

Now I am wondering whether previews are generated on every request, or whether and where they get cached for future requests. Unfortunately I do not see any documentation for this app that could clarify.

**Comment by skjnldsv** [comment]
> Now I am wondering whether previews are generated on every request, or whether and where they get cached for future requests. Unfortunately I do not see any documentation for this app that could clarify.

Hey!
That is a good concern to have. Previews are generated on demand if and only if, they don't already exists. Previews are cached by the power of four. Meaning we'll generate only from 64px to the max (64, 256, 1024, 4096) and we will only give you the closest image to your request

You can find one nice blog written last year (it slightly changed since, but you'll get most of it) https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/

**Comment by hiranchaudhuri1** [comment]
I am sorry John but you are a bit fast on closing issues.

The blog post you referenced only anwers part of my question. So all I know is "the preview is generated upon request if and only if it does not already exist". Yep, somehow I assumed so.

Now where is this preview stored? As I mounted my external storage as readonly it must not be there. So the question is whether Photos has an alternative thumbnail directory  or not. Do you have a description of that?

**Comment by skjnldsv** [comment]
It's stored in the appdata :)
I'm a bit fast to closing because this repository is for issues and features. For questions you should search the forum, most of what you ask is already answered there :wink: 

> So the question is whether Photos has an alternative thumbnail directory or not.

Check the documentation about appdata location. Read a lot about it, this can be a complicated step if not done properly.

Cheers!
John
